name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cxx: [g++-10] # clang++-9 is currently unsupported by pmm
        std: [14, 17, 20]
        build_type: [Debug, Release]

    steps:
    - name: Print Configuration
      run: |
        ${{ matrix.cxx }} --version
        echo std=c++${{ matrix.std }}
        cmake --version

    - uses: actions/checkout@v2

    - name: Configure
      run: cmake -S. -B${{ runner.workspace }}/build
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
            -DCMAKE_CXX_COMPILER=${{ matrix.cxx }}
            -DCMAKE_CXX_STANDARD=${{ matrix.std }}

    - name: Build
      working-directory: ${{ runner.workspace }}/build
      run: cmake --build . --config ${{ matrix.build_type }} -j2

    - name: Run Tests
      working-directory: ${{ runner.workspace }}/build
      run: ctest -C ${{ matrix.build_type }} -VV

  build-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        std: [14, 17, 20]
        build_type: [Debug, Release]

    steps:
    - name: Print Configuration
      run: |
        echo std=c++${{ matrix.std }}
        cmake --version

    - uses: actions/checkout@v2

    - name: Configure
      run: cmake -S. -B${{ runner.workspace }}/build
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
            -DCMAKE_CXX_STANDARD=${{ matrix.std }}

    - name: Build
      working-directory: ${{ runner.workspace }}/build
      run: ls && cmake --build . --config ${{ matrix.build_type }} -j2

    - name: Run Tests
      working-directory: ${{ runner.workspace }}/build
      run: ctest -C ${{ matrix.build_type }} -VV

  build-macos:
    runs-on: macos-latest

    strategy:
      matrix:
        std: [14, 17, 20]
        build_type: [Debug, Release]

    steps:
    - name: Print Configuration
      run: |
        echo std=c++${{ matrix.std }}
        cmake --version

    - uses: actions/checkout@v2

    - name: Configure
      run: cmake -S. -B${{ runner.workspace }}/build
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
            -DCMAKE_CXX_STANDARD=${{ matrix.std }}

    - name: Build
      working-directory: ${{ runner.workspace }}/build
      run: cmake --build . --config ${{ matrix.build_type }} -j2

    - name: Run Tests
      working-directory: ${{ runner.workspace }}/build
      run: ctest -C ${{ matrix.build_type }} -VV
